### ISSUE TITLE
Self-signed certificate in https://www.rokers.io/

### ISSUE THREAD

**Issue by gmacario** [robotrokers/robotrokers.github.io#23]
See screenshot

![image](https://user-images.githubusercontent.com/75182/27917931-c1302dfa-626d-11e7-8800-b3bcce83bbc9.png)

**Comment by gmacario** [comment]
@ludusrusso Anyway you know the trick, right?

See https://gist.githubusercontent.com/gmacario/2c11a927bfb9fa33326bd20fe28a85c7/raw/764d117d1f27924de5902d60ef1e4532bf3d92ab/docker-compose.yml

**Comment by ludusrusso** [comment]
@gmacario tnx! I think I cannot use it since the site is hosted on github pages directly!

**Comment by ludusrusso** [comment]
I've should have solved using cloudflare!

**Comment by gmacario** [comment]
@ludusrusso 

> I cannot use it since the site is hosted on github pages directly!

As a matter of fact, my blog is also hosted on GitHub pages, and I can access it as either <http://gmacario.github.io/> or <https://gmacario.github.io/>.

IMHO you should terminate the SSL for www.rokers.io on *another* host where you just need to run <https://github.com/DanielDent/docker-nginx-ssl-proxy>

**Comment by ludusrusso** [comment]
Solved!!!!

![schermata 2017-07-06 alle 18 48 07](https://user-images.githubusercontent.com/8146506/27922560-bd795ade-627b-11e7-8615-d288ace3be4c.png)
