### ISSUE TITLE
Link to homepage from blog posts broken

### ISSUE THREAD

**Issue by gmacario** [robotrokers/robotrokers.github.io#8]
Steps to reproduce:

1. Browse a blog post - for instance: <http://www.rokers.io/makers/educativa/teorica/2017/05/28/contributions.html>
2. Click on the ![rokers](http://www.rokers.io/img/logo.png) icon at top left
3. Instead than linking to <http://www.rokers.io/index.html>, the browser tries to open <http://www.rokers.io/makers/educativa/teorica/2017/05/28/index.html> which returns "404 - File not found"

**Comment by gmacario** [comment]
Wow, super-fast bug resolution!

**Comment by ludusrusso** [comment]
Solved! TNX
